import Header from "components/Header"
import User from "components/User"
import Head from "next/head"
import githubApi from "lib/api/github"

import type { NextPage } from "next"

export async function getStaticProps() {
  const res = await githubApi.getGithubUser()
  return {
    props: {
      user: res,
    },
  }
}

const Home: NextPage<HomeIndexProps> = ({ user }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen bg-green-50">
        <Header />
        <User user={user} />
      </main>
    </div>
  )
}

export default Home
